name: Test Gradle build script

on:
  push:
    branches: [ "ver/*", "feat/*", "dev/*", "expr/*", "ench/*", "impl/*" ]
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        base_jdk: [19]
        graal: [latest]
        os: [ubuntu-22.04]

    if: "!contains(github.event.commits[0].message, '[CheckSkip]')"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout action
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up GraalVM ${{ matrix.jdk }}
        uses: graalvm/setup-graalvm@v1
        with:
          github-token: ${{ secrets.GH_PAT }}
          java-version: ${{ matrix.base_jdk }}
          version: ${{ matrix.graal }}
          cache: 'gradle'

      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com" && git config --global user.name "github-actions[bot]"

      - name: Run Gradle
        run: ./gradlew --stacktrace
