name: Close invalid PRs

on:
  pull_request_target:
    types: [ opened ]

jobs:
  run:
    if: ${{ github.repository != github.event.pull_request.head.repo.full_name && !startsWith(github.head_ref, 'feat/') }}
    runs-on: ubuntu-22.04
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "When you create a Pull Request, please create the branch name in `feat/<pr-name>/<version>`."
